### ISSUE TITLE
/move support.

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#10]
Good GOD I must annoy you. Sorry >..< But yeah I know you said char name does move, but is it possible to patch in support for char ID number? Reason I say is, some people's char names have spaces in them. And if they are on a char that has a space...well, the format /move charname areaname breaks since it thinks the space means the next part of the name is the area now.

**Comment by stonedDiscord** [comment]
char IDs already work and you can replace spaces " " with underscores "_"
