### ISSUE TITLE
Suggestion/Question: Upgrade the user level required to use the /area <no number> command.

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#12]
Not sure what this would break or not, but would it be possible to prevent a normal client from just using /area and seeing the connected users on the list, I.E: Restricting that info to mods?

**Comment by stonedDiscord** [comment]
I don't see why you'd want to do this, it only makes sense that the users can see how many people are in the areas so they can decide which area to join.
I could make hidden areas that don't show up on the list and if you really want to, you could make all areas hidden but that sounds like a terrible idea to me

**Comment by Catalylia** [comment]
**Personally speaking, I _agree_ with you actually**. But my members are a different story. Regular users and mods feel it's a privacy issue when anyone can see how many people are in an area and they prefer it being mod exclusive.  Having hidden areas would be a good middle ground I think. Though I do think as you said, making them all hidden is a horrible idea.

**Comment by stonedDiscord** [comment]
c97f5cc5eecde236e88115ad2e62e997a4c998a3
