### ISSUE TITLE
/switch IS broken.

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#13]
Using the /switch command for regular members, I.E: Going from Layton to Adrian, will not work for regular members it seems. Unless that is intentional, but your notes don't seem to indicate that. >..>

**Comment by stonedDiscord** [comment]
Unauthenticated users can only use /switch without any parameters and it works fine like this.
/switch Layton
is a mod command that will kick the user playing Layton back to charselect
/switch Layton Adrian
is a mod command as well and will switch Layton to Gumshoe without the charselect and without the shrink bug, this alse replaces the /send hacks

**Comment by Catalylia** [comment]
Okay. I suppose a better question is this then: Is there a way to create a separate command that will allow normal users to change their char without shrinking their window?

**Comment by stonedDiscord** [comment]
no, it's a client bug.
displaying the charselect shrinks the window in the current client version, because thats how fanat decided to resize the window

**Comment by Catalylia** [comment]
Hmm...so how do commands like the the mod char force change /switch char1 char2 and the /change command bypass it? Meh. #Blame Fanat.

**Comment by stonedDiscord** [comment]
to show the charselect the server sends DONE#% to the client
that shrinks the window
/switch char1 char2
sends CID#newid#%
which doesn't show the charselect
and i don't know what /change is or where to find it

**Comment by Catalylia** [comment]
/change is in a different server program. It works similarly to the mod command skipping the char select. Only it's a "proprietary" server version. >...>  (I.E no one but that server has it.) I was just wondering if it were possible to do is all. Like a way to allow a client without mod/admin access to switch themselves to a designated target like the mod command, but only working for themselves (I.E : They can't switch other players.) and bypassing the DONE#% send off. Though the only way I see that happening would be with a separate public user command. <...<

**Comment by stonedDiscord** [comment]
It's "proprietary" because it's most likely 90% ripped off this. I can tell because "Demons Server for Demons" started using their "proprietary" server a few months after I released the source code to serverD. Also they are the ones who pushed me to doing it with accusations coming from their userbase that my server contains malware or something.

But the /change command to let users switch themself is a good idea, I will add it.

**Comment by stonedDiscord** [comment]
8981214f4b6531a06f6c7c0e97638008b673cacc
