### ISSUE TITLE
I'm an idiot, there is no doubt.

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#14]
I still can't seem to get Replays to work. 

I have a Replays folder I made in the main directory serverD is in. Originally I tried to make a textfile for it with the proper name. (Of which I can't remember atm because I'm not home and I am a derp atm.) I also  tried making a replays folder in the base. No dice. I think I also tried to just put the file straight into the mian directory without a folder. I atm took them out, though the replays folder is still there, empty. I have replay enabled and a 400 line cut off. But it does nuttin. 

**EDIT : (Though to be honest, on the settings I see replay option activates, I.E : 1, and replay line = 400. But not...an actual line on where to save them atm. Which is prob the issue now that I think on it, _and have stopped being a bloody derpface._ but why the hell wasn't that line there in the fir-nvm Just what is said line if there is one?)**

On an unrelated note, can't find the "Take On Me" release, prob because it simply ain't actually there yet, but in case it is and I am a derp, I wanted to ask.

**Comment by stonedDiscord** [comment]
the replays folder belongs in the base folder, it saves and loads replays from there.

these are the settings.ini options to enable saving replays:
replaysave = 1
replayline = 400

to load a replay you need to be server admin and type /loadreplay filename.txt in the ooc chat

**Comment by stonedDiscord** [comment]
Take On Me is not yet built

**Comment by oldmud0** [comment]
we have to wait until sD adds the backdoors on the new build

**Comment by Catalylia** [comment]
lol wat. Mud wai. Also, okay. I'll attempt that and hope it auto creates the file.

**Comment by stonedDiscord** [comment]
backdoors? no
the last time i tested it, I ahd 119 characters but I couldn't chat at all and I want to fix that before building.

**Comment by Catalylia** [comment]
Well do be fair that's not your fault, the being unable to chat thing, it's AO 1.7.5's. There are versions of AO that let you use up to 240 chars, but for people to see you, they would have to have a version that did the same. AO normal, as far as I know, only recognizes 102 char slots from 0-99, 100 being zetta, and 101 being null. After that it will not process another char.

**Comment by stonedDiscord** [comment]
i think i fixed it
normal clients get up to 100 chars now and web clients get all chars
i don't know of a client that accepts 240 chars and i will not support it, unless i get a copy maybe
