### ISSUE TITLE
Passwords~

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#15]
Obviously you were gonna get a ring from me.~ Question was when. Alright Here is my problem.

As the title says, passwords are not working for me. Let me explain what I did in case this is my derp.

In the areas file I have something like this.

[Areas]
number =22
1 = xxxx
2 = xxx
.
.
.
22 = xxx
[filename]
1 = xxx
.
.
.
22 = xxx
[password]
21 = Whatevthefrigthepassis
22 = Whatevthefrigthepassis
[hidden]
18 = 1
19 = 1
20 = 1
22 = 1

Now. Hidden areas? Beautiful, they do not show up on the list for a reg client (Mods still see them but that's perfectly fine, just meant I had to un-mod myself to test it because I had OP.txted my IP/HDD.) Now. I use /area 21 as a reg client to get into area 21...(Which should be number 22 on the area text because in server counts lobby as zero, not one, obvs....) and it lets me straight in. No prompt no nothing. I'll test  a little more but...

Did I derp something? (Yes 21 isn't hidden on purpose.)

**Comment by stonedDiscord** [comment]
so far it only loads the password but doesn't check it

**Comment by Catalylia** [comment]
Ahh. Okay, so I'll just remove that from the server's txt in the meanwhile then. Thank you.
