### ISSUE TITLE
Another not-an-issue-but-suggestion

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#16]
Generally speaking I think serverD is damn well near perfect. I mean seriously. It's a small foot print that does a hella lot of work. As such much of what this post is asking for is fringe support and stuff that is for "polishing up."

/roll is a wonderful thing.  It looks clean and is far neater than it used to be. 
Now here's is an odd request. 
Remember how you used to have it where it was "spoof able" with numbers? Can that be re-implemented only with a different style? Such as...

/roll 3 = $HOST User1 rolled 10 out of 18 
As in, you rolled three dice. 
Or, alternately, alternate  /roll into something like
/rand 200 = $HOST User1 rolled 134 out of 200
As in, generating a random number.
(Or if you use /roll 1, it would flip a coin instead of rolling a dice but I think a /rand 1 would work better in that situation.)

Also, one person in particular does not like the fact you can still roll a zero, though they seem to be alone in that. (Personally speaking I think it's hilarious you can roll a 0. But meh. I felt I should mention it.) 

Reason I ask this is because a lot of people seem to love to play games with random gen numbers and a single roll doesn't cut it. I have ended up making them an google sheet, (I'm srs, lol, I can give it to you if you want thought I doubt that would help anything.) but they would love something more integrated.

VVVVVVV This is low priority since it's just frills~ VVVVVV

As I can use AHK scripts to "Auto Post" messages into server OOC at set intervals, I don't necessarily need a function for it, but not everyone can do that/ runs the server on their own pc and doesn't want AHK jacking their mouse to do something every 30 mins or so.) So I was thinking that perhaps there could be a text file, similar to how the gimp file works. 

I.e If "Auto message = 1" in the poker/settings It checks the oocpost.txt (Or whatever the heck you wanna name it) And that doc would have like a setting for time = 600 (I dunno, I am counting seconds, maybe that time setting would be cleaner in the poker. ) And then a list of comments, one comment per line, of messages the server will randomly choose from to post every ten mins or so (Or whenever they set the timer to.)

**Comment by stonedDiscord** [comment]
i made a broadcaster plugin, download the .dll file and put it in the plugins folder

**Comment by Catalylia** [comment]
Oh, thank you very much.

Edit : I'll need to play around with this a bit to figure out the format, since it does not seem to be working for me. (I mean the plugin itself comes up and starts, but the auto message ain't workin'.)

**Comment by oldmud0** [comment]
What is the plugin format? What entry points do I need in my DLL?

**Comment by Catalylia** [comment]
^ I am gonna assume you don't need to mess with the DLL and instead use the plugin's interface itself. I was Assuming that "CT" was the Broadcaster's call name and  The AUTO was the message but that did not seem to do anything for me and I admit to being code retardate. ((Or rather, I have not practiced any real coding in like freaking six years. >....> Time wai are you so short. I nee more of you in a day. )) 

Then I was like. No Derp face what if you need to keep the AUTO as a call function for the code and you just type your message in one of the pairs of Octothorpes. Then I went nutso trying different shat.

**Comment by oldmud0** [comment]
No, as in how does one make their own plugins.
EDIT: Okay there are a couple of PE exports:

```
PluginDescription
PluginName
PluginRAW
PluginVersion
SetMessage
SetTarget
StatusCallback
```

**Comment by Catalylia** [comment]
Oh. Well like I said. Derp face here.

**Comment by stonedDiscord** [comment]
CT#username#YOU COULD ADVERTISE RIGHT HERE#%
that is the command for OOC chat

**Comment by Catalylia** [comment]
Yeaaaah like I said above I was trying that and it err...still was not working for me, but I'll screw with it a bit more since it most likely is my end and I'm being a derp. Thank you for the clarification though. I do appreciate it,
