### ISSUE TITLE
WEEEELP Something is broken

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#17]
Not the plugin issue, though I still don't have that fixed up. I doubt that has anything to do with this though. 

Regular members seem to no longer be able to lock rooms. Is this intentional or no? Mods can still lock um fine....

**Comment by stonedDiscord** [comment]
yea, random people locking themself alone in a room appearently is a thing now
that's why i changed it to mods only

**Comment by Catalylia** [comment]
Err welp. Was never A thing where I was...but okay ~ 
(Rather people locked it to prevent interruption on private convos or cases).

**Comment by Catalylia** [comment]
Done a bit more research and I can see how you would feel about that being an issue, though I do wonder if there can't be an option instead to allow or disallow regular client commands such as locking, as while some people may lock themselves in a room for one server, in another place such actions may not even occur to people. 

Or. Alternately, allowing people to create dynamic rooms that are destroyed upon leaving...(though that is a bit much since that would prob require something like the server creating a dynamic folder almost like a mini server and that would be prob more trouble than it's worth...)

**Comment by king5327** [comment]
I don't think it's that complicated, actually. It's more or less the same as marking every new room with a unique identifier and then doing what messages do now: only get passed around to people with the same identifier.

**Comment by Catalylia** [comment]
Well being complicated and being worth the effort design wise are two different things. =/ I mean it has been done before, but the question in my head is more is it needed.  I would much rather prefer locking for members being re-added, maybe with a safe guard to prevent one IP/HD client from locking every room except main, as opposed to removing the lock option from normal members, as that just strikes me as wrong. 

(I know you can't lock main, I was saying there needs to be an expansion upon that feature. rather than having it **just** do that. Maybe preventing one regular client from locking more than one room? ) 

I mean it either forces mods to stay in a room that a member wishes locked for privacy, which defeats the purpose of member privacy, or it forces members to constantly spam a call for /area to check if they are talking in private and not hosting a conversation for an area scout.
