### ISSUE TITLE
Some semi-security semi clean up suggestions.

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#18]
If it is possible, disallow people from putting the "$" in front of their names in OOC. This way they cannot impersonate the host or the bots. 

Also, perhaps different colors for OOC? Like a mod typing in ooc would be like green and system stuff would be red? (Or stuff sent by the admin/via $HOST) _In b4 brand new color for both because why the hell not_ - _SHOT DED_ 

Or alternatively, adding a mod only color in char instead, not like locking the existing ones, but a brand new one that is not case related?

Also....is there a way to like...ban a range of IP's? Semi Recently had to deal with a troll that kept changing his last two IP octet numbers. Hella annoying to snipe IP by IP without wondering if I was legit sniping someone else in the process. He also had no HDID so GG me, no res.

Also that "being able to set permissions for members /lock" might be extendable to other functions, similar to how you can use the char.ini's server side to make a char passworded or undj'd.

**Comment by stonedDiscord** [comment]
afff7648abebeb8ca2e229a648f63ea23072cb74
