### ISSUE TITLE
A strange glitch.

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#19]
I encountered an odd glitch in the most recent build, "PUMP THE JAm" 

I have an area doc built with 12 areas for testing purposes. I hid the last three from reg member access and put passwords on the last two for shiz and giggles to test out if passwording was added yet.

When I use an area shortcut all the area short cuts work except the last one. Using the last one for area 11 teleports me back to one. 

but if I used /area 11, I am able to reach it. and it's the correct area. 

This is only happening to the last area. No other area seems effected but this. 

Actually scratch that, it's multiple areas.

**_Still double checking to see if this is my derp btw**_

**Comment by stonedDiscord** [comment]
sounds like an off-by-one, probably _not_ your fault
