### ISSUE TITLE
Music glitch when two players select the same song at almost the same time

### ISSUE THREAD

**Issue by DoctorMalboro** [stonedDiscord/serverD#2]
I've noticed that whenever two players select the same song at almost the same time, it causes the repeat to put the same song twice. Maybe checking that the song was already selected would avoid this issue.

**Comment by oldmud0** [comment]
By the way @stonedDiscord, when are you going to bring the forums back up?

**Comment by stonedDiscord** [comment]
exactly that is done in
Procedure TrackWait(*usagePointer.Client)
Line 647
If areas(wtarea)\track=track$
seems there is another thread race condition here, I will look into this

**Comment by stonedDiscord** [comment]
after getting spammed to death by WAKE ME UP.mp3 i must say this really is a terrible bug
