### ISSUE TITLE
Here I go again.~ 

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#20]
(TBH by now the only thing that bugs me is the member not being able to lock thing, dun't even need passwords tho they would be very nice. I think the serv is basically perfect otherwise.)

I keep thinking about features, but I'm not sure they are doable. So I will just place them here.

-Being able to cut out the sound of blips without cutting off the music. This is something of a bane in AO. Especially when putting the volume all the way down to zero cuts the music but the blips are still sorta there and so are SFX's. 

-Is there a way to make "Testimony" flash in the corner like AA? I know Fanat had the resource in the misc folder, but is it actually possible to use?

-I'm gonna assume banning IP ranges works like other commands in OOC unless it's strictly in the ban file. I.E: "/ban 45.78.34.12 45.78.123.254" as in /ban IP1 IP2. But what if you could multi ban people like "/ban IP1, IP2, IP3, IP4"? *_Might be a bit much there_

-The ability to reload an ini. As in if someone adds an emote to a char and want's to test it, they typically have to re-log. But if there was a reloading command for ini's, they would not have to. This could also fix potential issues that arise with ini's that were not loaded properly.

VV **This one is prob the most doable**  VV
- A timer. That's it. A simple timer like...

/timer 600 = Gives the player a timer that tells them when x time set is up, maybe updating every minute/five mins? Might be nice for cases or event countdowns for mods.

**Comment by OmniTroid** [comment]
The points with blips and testimony are exclusively client-side issues. Post a suggestion on

https://github.com/AO-devgroup/AttorneyOnlineQtClient

and I'll look into it.

And reloading the whole window as well as char inis and so forth should also be wholly feasible as a client feature.

**Comment by Catalylia** [comment]
Coulda sworn  at least for blips and ini's that it was feasible for a server thing. Testimony I was not sure. But I do agree it would be a cleaner thing if done client side and locally for those.

**Comment by stonedDiscord** [comment]
/ban 45.78.34.
already works like that
/timer 600
yeah i can add that

the others are client issues, not my biz

**Comment by oldmud0** [comment]
@OmniTroid A... working... custom... client?
![*takes off glasses*](https://i.imgur.com/ti8B9pu.gif)
WANT

EDIT: nvm it's not working

**Comment by Catalylia** [comment]
Just to clarify, you can ban more than one IP at once using the same command?

**Comment by oldmud0** [comment]
why do people refuse to learn CIDR notation

**Comment by stonedDiscord** [comment]
i'm not gonna add regex just to parse the stupid notation no one will ever use or understand

**Comment by Catalylia** [comment]
Lol, it's not an important feature like I said, but what does classless have to do with this? I was talking about two separate IP's in one command as in if there was more than one troll on a serv with diff locations. o.o _Is confused_ But ehh, it's not important.

**Comment by stonedDiscord** [comment]
/ban 45.78.34.
this should ban the entire 45.78.34.\* IP block

**Comment by Catalylia** [comment]
Oh. So it's for same IP subnet only. Okay, that's beautiful still though, but my suggestion was more for something like " 12.34.78.56 and 234.67.89.12 are both spamming trolls, ban um both" /ban 12.34.78.56&234.67.89.12" But like I said, that's unnecessary and prob would only help really large servers with a massive number of trolls at once time.
