### ISSUE TITLE
Moderator Command for Announcements

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#22]
Similar to how the serverD client can post a Host message to everyone, It would be great to be able to post to all areas (mods and above obviously) with a command.~ 

You can shoot me ded now~.

**Comment by oldmud0** [comment]
What's with the tilde after every line~? Lot of Japanese anime?

**Comment by Catalylia** [comment]
Not recently no. Been years since I actually watched anime.

No just happier than I have been in a while.

**Comment by stonedDiscord** [comment]
ooc does exacly that

**Comment by Catalylia** [comment]
OOC posts it to specific areas actually. Which is the way it should be. o.o I was talking about a command a mod could use that would like...put a banner or something and post a message **EVERYONE** in **every** area on the server could see.  

And yeah, preferably in OOC like $HOST. 

I am essentially asking for the $HOST message, but for mods. Like $Announcement or

||||||||||||||||||||||||||ANNOUNCEMENT||||||||||||||||||||||||||||
Text here text here text here.
|||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||||
