### ISSUE TITLE
"Enhancement" rather.

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#25]
After looking at the "animator" that was supposed to be for serverV's VNO, It makes me believe serverD would benefit from a sort of mini mod or "power user" level. Someone who could change the bg or undj/dj people for purposes of keeping a case on track.  _Possibly_ also lock rooms so if there is an event going on, or alternatively, if they are running an RP/case event, they can alter the server/keep the peace without having to call a mod all the time. (They might be able to mute, but unsure about that one.)

A secondary thing I was thinking of is more of a GUI thing and isn't terribly important. **(Actually it's not important at all so meh. )** But when clicking on the headers of the IP, HDID and Chars, is it possible to make the list organize them in order?

**Comment by stonedDiscord** [comment]
1. chill
2. i don't really care about the GUI version at all

**Comment by Catalylia** [comment]
Aight I'll chill lol.

**Comment by oldmud0** [comment]
> i don't really care about the GUI version at all

Thank you

**Comment by stonedDiscord** [comment]
The GUI is a leftover from MITMserver which was more like a debugging tool than a server
