### ISSUE TITLE
OP.txt HDID registering and HDID registering on AO2 clients.

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#28]
Oh hai, it's a me, Mar-*shot ded*

Alrighty. As the title says. When mods use /hd to obtain the HDID of users, for AO2 clients, their Hard drive ID shows up as only " AO2". 

Furthermore, the OP doc used to accept both IP's and HDID's for auto login. Now it no longer seems to be able to register HDID's and only register's IP's. 

Are these on purpose or unintentional?

**Comment by stonedDiscord** [comment]
AO2 doesn't have the HDID feature, instead it sends it's version.

**Comment by Catalylia** [comment]
Well that's fine except it means ALL AO2 clients are gonna show up as AO version X.X.X when connecting to a server, which really does not help for logging history when trying to cross check for an IP spoofer, and you can't use HDBan on said AO2 clients unless you want to ban ALL AO2 clients on that version.


Buuut that's an issue to bring up with AO2 not here.
