### ISSUE TITLE
serverD repeatedly restarts when starting

### ISSUE THREAD

**Issue by Lewdton** [stonedDiscord/serverD#3]
With the new update, whenever I publish the server and start it, the serverD program restarts over and over again

**Comment by oldmud0** [comment]
What does the log say?

**Comment by Lewdton** [comment]
Server Log
http://pastebin.com/DELazGHs

Server crash.txt
http://pastebin.com/GC4GtfzD

**Comment by stonedDiscord** [comment]
it crashes when no plugins are loaded
fuck me
