### ISSUE TITLE
BG changing issues.

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#30]
Resident...bug tester here I guess? 

I'm not sure why, but with the newest build of serverD, / bg seems to intermittently work. It might have to do with the animator status interfering somehow, but even when I manually log in as mod, the bg doesn't seem to change properly for all users. Or read the bg properly from their files. Reloading the server doesn't seem to fix the glitch, but _restarting it_ usually fixes it, which tells me it's properly configured, but there may be some sort of clash or permissions conflict? It's only happened to me with the latest version.

**Comment by stonedDiscord** [comment]
animators can change the bg
can you describe when how many users do not see the updated bg?

**Comment by Catalylia** [comment]
It's a mixed reception. Sometimes the user changing the bg themselves does not see the bg, sometimes they do but others do not.  I've tried as both animator and moderator logged in. Sometimes I know I have the files for a specific bg and I /bg to it, but nothing changes for me until I re-copy the same bg back into my folder, other times people are able to see a BG changed an hour ago just fine, but when they leave and come back it's suddenly gone. (It's a very weird issue. ) 

Originally I thought this was because how the server I was on was setup, because I have a few "Custom" areas which are tied to a folder called "CustomOne" where I can load a bg unto it for testing how it looked. I thought maybe there was an issue with custom files, but sometimes people are unable to change the lobby itself, and the lobby isn't tied to a custom folder. 

The weird issue in itself is that this does not always happen. And usually if I close serverD and reopen it, boom, it's working properly again for like, 24 hours or so. Then this happens again.

**Comment by stonedDiscord** [comment]
![image](https://cloud.githubusercontent.com/assets/10584181/22429137/dfa1f7da-e709-11e6-9ddf-0f2c360a5d26.png)

tbh this code is way too simple to fail
what version of AO are you testing this with?

**Comment by Catalylia** [comment]
1.7.5 and 1.8. It's only happened with this version, but that does make me think a bit. It never had an issue prior, but does the new serverD have anything that would make it less "resource friendly" if multiple instances of it are running at once?

(I don't think this is the issue, but gotta ask anyway.)

Basically speaking it's like this : 

On this computer, there are two serverD programs running. A version 1300.146 and a Version 1334.147 One on port 27050, the other on port 27053 is there any possibility of "cross talk" or leaking going on here? (Prob being stupid asking this but meh.)

**Comment by stonedDiscord** [comment]
they are completly independent of each other but i wouldn't run 2 in the same folder

**Comment by Catalylia** [comment]
Two different folders but both folders are sitting on the desktop.

**Comment by stonedDiscord** [comment]
then it does not matter

the background copying does make me wonder
does it work when you do /bg twice?

**Comment by Catalylia** [comment]
I tried yesterday to change the BG multiple times. Ironically it was on a client I had been able to change the BG on an hour prior. It did not work. Basically I did the following> 

First : /bg CustomNine in Lobby. > Lobby changes to what I had in CustomNine. ( A garden area.)
/bg CustomEight in lobby > Bg changes to CustomEight, like normal. 

I don't change the bg for about an hour until someone comes in who does not have that new BG. so I try to /bg CC1 (The name of the lobby bg.) Does not work. Try it again. Still does not work. I try /bg CC2 (Another area.) Still doesn't work. I use /ip> Works. I try logging in as admin. > success. > /bg > still nothing. Try a new client (animator.)> This works.  Try kicking new client from old one > I kick the animator. I try to change the bg with the admin client > NOW it works.  

I tried also to restart the server, and as I said, this usually also works.


If it was an issue with the client itself, I wouldn't be able to use other commands and the command wouldn't suddenly start working again after another client did it.

**Comment by stonedDiscord** [comment]
i think when someone joins the server and does not have the background, changing it to another one after that does not work.

**Comment by Catalylia** [comment]
That's the funny thing, It used to work all the time.  People used to come into the server all the time and if they were new and never had our files, the mods would usually change the bg to default for them while they got the files, so their client wouldn't bug out from errors. 


However, this is just one example, I've tried with people who have both and it has also not worked...


Re: Another users experience >


Snake (999): So Area 8 in Ruby's RP is a safehouse. Area 9 would be the area outside of said safehouse.
MilaNexus: Corect.
MilaNexus: Correct*
Snake (999): I'm in the safehouse, looks fine to me.
Snake (999): I need to leave for an expedition, so I exit the safehouse and go to area 9.
Snake (999): First thing I notice about area 9 is that it's not the right BG. At least, not the one we'd used prior.
Snake (999): It looked like the background "role play"
Snake (999): Which there's a picture of just so you have it.
Snake (999): I proceed to area 10, and the bg changes as normal.
Snake (999): I go back to area 9 having finished things there. Die in area 9 but that's not really relevant.
Snake (999): Go back to area 8 to spectate and what was once fine as a safehouse bg is now the "role play" background.
Snake (999): I open a new client and go to that area and it looks fine.
Snake (999): It seemed to me like everyone else was seeing the "ouside the safehouse" bg fine too. Nobody else commented on it.
Snake (999): I definitely have the files for her RP. So I found it odd.
MilaNexus: Mind if I post that to him?
Snake (999): Sure.
MilaNexus: Discord that is.
MilaNexus: kk.

**Comment by stonedDiscord** [comment]
so the bg did change but to the wrong one?
and only for one guy?

also did it kick him to charselect by any chance?

**Comment by Catalylia** [comment]
That is one example, but it seemed for him to change to the original bg that was  in CustomEight. (Keeping in mind he already replaced the BG in custom eight with the role play's files days before.)

I double checked with him and he says, that he had not been kicked to char select during any time during that. These role plays usually have designated areas and characters assigned so no one crashes into each other.

**Comment by Catalylia** [comment]
This issue appears to happen less often now, but still occurs. It seems to no longer effect /bg anymore, or at least not as much, but now instead *just* effects bg's on an area. I.e : If an area has "CountyCourt" for example, as it's defined area in the ini, it will show up to someone walking n as "default" until it is /bg'd. This seems to happen randomly and only to areas that haven't been in use for the past few hours.

**Comment by stonedDiscord** [comment]
sometimes old clients miss a few commands and the bg might not change

**Comment by Catalylia** [comment]
This is on 2.3.5 I am experiencing this problem however...Hmmm...strange.

**Comment by Catalylia** [comment]
The newest versions seemed to have subdued this issue so I am closing this. It's not so prevalent anymore.
