### ISSUE TITLE
v2.150.1337 - Stability Issues.

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#31]
I note after updating to the most recent version, occasionally members are unable to speak in Main Chat, only OOC. This happens to AO2 and 1.8 / 1.7.5. It lasts for a few minutes randomly, but seems to correlate with high volume.

**Comment by Catalylia** [comment]
Disregard this issue. I figured out the problem. Someone's been DDoSing servers with the intent of crashing them across AO and TFL seems to auto boot them off after about two minutes instead of crashing. Which is cool for TFL to do that but...make me thing there was a problem with the server instead of a DDoS trying to crash it. Lol.

**Comment by stonedDiscord** [comment]
i could probably find the solution if i had the logs
