### ISSUE TITLE
[Suggestion] : Load Option

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#32]
You might not go for this one ,you might go for it, but I was thinking about this recently ; 

What if it were possible for a person to adjust how many characters are loaded, by default, for their server? For example. Say I have 240 characters on the roster. I can choose for the server to load 100 by default for those who connect to it.  If a person wants the rest, they would use "/loadm"(music), "/loadc"(chars) , " /loadall "(all) or something similar. the same can be applied to music. 

This would be done for the sake of speeding up connection to a server, but also would help those people who still have older clients...((Like those peeps who still use 1.7.5 for example.....))

This is something I remember you having before. ((I.e, optional music loading))

**Comment by stonedDiscord** [comment]
clients would have to reload and there is no safe way to remember "user" settings as there is no user accounts or anything
