### ISSUE TITLE
(Issue)serverD does not seem to load the entire list for all clients?

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#33]
This is actually something that...might make my last suggestion about adding an option for /loadx to be more viable.

AO1.8 does not seem to load the entire char list. It only loads the first 100 for some demented reason. 

Good news! This means 1.7.5 clients still live and are able to connect to a server with 175 chars. 

Bad News! 1.8 can see all chars, but can only choose from the first 100. Meh.

**Comment by OmniTroid** [comment]
As far as I know, it's because it's impossible to tell apart 1.7.5 and 1.8 clients.

**Comment by stonedDiscord** [comment]
there is a poker.ini setting for that called
CharLimit
it's set to 1 by default, setting it to 0 will disable the limit and break 1.7.5
