### ISSUE TITLE
[Suggestion]Support Expansion?

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#34]
It's not exactly an * issue *  per say but more future proofing. I note that serverD usually starts derping when it hits 101 areas, most likely due to what it was built around to support. I do remember seeing something in it's code prior for 300 chars as a support as well. 

Increasing the 300 chars isn't extremely important, (Unless it's easy then might be nice. ) But the 100 area limit is something that I have been working and simply dealing with for a while. It's not really a real bother because when I sit down and think about it it's like " God damn do I really need all these areas? " And often the answer is yes, but maybe I can swap one out and just /bg something.  So I do that instead. But it may be something to think about for others when Role Play is so ....everywhere on AO recently.

**Comment by oldmud0** [comment]
Welcome back. And no, you do not need 100 areas.

**Comment by Catalylia** [comment]
Hallo! 
Ehh like I said the Area thing isn't * as * important. I have more or less been sitting at the 100 area limit and have been fine. Just shuffle areas I don't need out as needed and I have a set 15 put aside for people to use specifically as a custom set. Chars I am a bit more concerned over.

**Comment by oldmud0** [comment]
Wait, what? What in the world are you using 100 areas for?

**Comment by Catalylia** [comment]
I don't believe I am the only person which such a high area count but I might be the only one using serverD for it. (Not certain, don't quote me on it. ) For reference, the server is " The Flaming Phoenix". It's primarily an RP server. It's area count is so high due to hosting multiple RP's over different time zones, where there isn't easy access to a moderator. (Or when I am at work / asleep. ) The custom areas let people have their own way to change areas since you can just drop files in the custom folder and it changes, which is why I have 15 of them, but otherwise people us the other 85 stock areas for different places, including the lobby.  I have a fairly decent mix area wise and have tried to organize them by type.  The server also has 272 characters on the roster, including 15 "Persona" slots which function the same way as the custom areas, letting people use characters not on the roster. There are also 5 " GM" slots which are the same thing but recommended for GM's to use. * shrugs *  The characters only recently rose to 272, used to be 230~ ish for about...four months ish? The areas have been at 100 for maybe six months. 

At the moment I don't really have much of an issue area wise, as I said I shuffle when necessary.  I was just mentioning it since if character increased support was viable, would be nice to also " future proof" area wise.

**Comment by Catalylia** [comment]
Additional Note : This is why I first noticed the problem with area folders not changing properly, it was the Custom Areas that were derping first.

**Comment by stonedDiscord** [comment]
fcc710e8d300d01760e3450d22007ae629ad9662
