### ISSUE TITLE
[Issue/Bug] Random Crashes

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#35]
The latest version released for bug fixes seems to crash randomly and often for me. I can't figure out why but it makes the server begin glitching out and un-closable save for a task manager or command prompt close. I can't make any solid connection as to why, but it seems to happen often when moderation commands are used like /ip or /gimp. ((This isn't a definite however. )) 

I also notice that the second to latest seems to have  trouble staying on the master list? It's not that the adverter is in need of tweaking ;it's that over the past few weeks I have noticed logging into it and seeing the adverter "public" setting was off even though I was sure it was set to on. Almost like it self-reloaded. ((Not sure if this is just an issue I am experiencing however. ))

**Comment by stonedDiscord** [comment]
this has been reported by other users as well
i'm trying to reproduce it

**Comment by stonedDiscord** [comment]
rip
