### ISSUE TITLE
No sound on android device

### ISSUE THREAD

**Issue by jochuan** [stonedDiscord/serverD#36]
I am trying to play it on my Chrome on my Samsung Gran prime but there is no sound

**Comment by stonedDiscord** [comment]
try playing the same track again

**Comment by jochuan** [comment]
It still don't work and there is a lot of other visual bugs too

Em 04/01/2018 18:13, "stonedDiscord" <notifications@github.com> escreveu:

**Comment by stonedDiscord** [comment]
webAO is far from finished, sorry

**Comment by stonedDiscord** [comment]
this has nothing to do with the server software, closing
