### ISSUE TITLE
[Issue/Bug] Music Loop doesn't work in other areas

### ISSUE THREAD

**Issue by Pacmanster** [stonedDiscord/serverD#38]
The music loop features seems to work only in the default area, it refuses to work in any other area.
I'm using the ServerD portable, not the console version.

**Comment by Catalylia** [comment]
-- Huh. I did not notice but can confirm on my end. No longer loops.  I've just not been using loop too much recently but yep. Doesn't work anymore.

**Comment by stonedDiscord** [comment]
57300c3a6758a2b052dfc1972cab021547b2ed0e
fixed it

**Comment by stonedDiscord** [comment]
new build is ready
