### ISSUE TITLE
<Enhancement> Music Loop Improvement?

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#39]
This has been in my head for a while but I was wondering how viable/useful a change to how the music loop works would be. Currently you can set any time for the song to loop from, so you can cut out the ending of said song and just loop it to the beginning if you so desire. But I was wondering if it were possible to add a second variable for where to *start* the loop. I.e : Like in an AA game where the song starts off, and then keeps repeating without replaying the beginning or the end point by looping the portion inbetween. I.e : 

Song.mp3, * 20, 300

Specifying : Play song > stop at 300 seconds and start playing from 20 seconds. 

Also Off topic : Yes. People do read those titles. *shot*

**Comment by stonedDiscord** [comment]
the server can't tell the client to start in the middle of the track
