### ISSUE TITLE
Master server IP has changed.

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#8]
Perhaps there should be a way to change the server IP serverD connects to? Unless there is and I am blind. (Not going to deny that if I am.) Either that or an updated master serv build would prob help.

**Comment by Catalylia** [comment]
Apparently not being home meant I was misled. People did not read it would not reset till the first. Sooo ignore this. Well not IGNORE it. I still would like to know that...

**Comment by stonedDiscord** [comment]
in case someone else missed it, you have to replace the masterserver.ini in the base folder just like you do with the client
