### ISSUE TITLE
Area specific Mass Mute.

### ISSUE THREAD

**Issue by Catalylia** [stonedDiscord/serverD#9]
I am probably annoying as all hell. Sorry for that.

This is more a suggestion post than an issue post.

But It would be nice for a command that was mod level that allowed mods to mute a specific area of people. I think with the recent server version being able to identify where people are area wise, this would be pretty possible and useful. (As opposed to just giving the mods access to Muteall since that is kinda iffy.)

Also brings to mind the ability to push someone to another area instead of to another char with something similar to /send...without borking said user. (As last I checked using /send borked a person's ability to play music and they still showed up as the char they were previously in the char list.)

Also, while the auto presentation of evidence is a great feature. It IS a bit intrusive and annoying. Is it possible to customize that char wise/text wise or, better yet, make a built in "Auto greeting/auto messenger" for the OOC? I've been using AHK scripts for that recently and it would be nice if it were possible to integrate into serverD.

**Comment by stonedDiscord** [comment]
71a4ff8735be86cd8086fc3921aede1283ed904a fixed it
ahk? autohotkey? well, maybe i could make a plugin for that

**Comment by stonedDiscord** [comment]
74d0dd8a6fe7f0f573e3cab11fdfe3feccb1955e MOTD

**Comment by stonedDiscord** [comment]
/send is only for testing stuff and should not be used
you can do /switch charactername to drop someone to charselect and you can use /move charactername areaname to move someone to another area

**Comment by Catalylia** [comment]
-/switch is a tiny borked but that is AO's fault and not yours.
- the format "/move area1 area2 does not seem to work. But might be our end, will test a bit more.
  ![borked](https://cloud.githubusercontent.com/assets/18173214/14934031/76bbbcb8-0e71-11e6-8aaf-a16ace72a148.PNG)
  -also possibly the instance I was running but the live logs seem borked.

**Comment by stonedDiscord** [comment]
/move Area2 areaname
 /switch oldcharacter newcharacter

the A in Area# needs to be uppercase
